---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'traefik'
        static_configs:
          - targets: ['traefik-dashboard-service:8080']
      - job_name: 'kosarica-microservice'
        static_configs:
          - targets: ['kosarica-microservice:8080']        
kind: ConfigMap
metadata:
  name: prometheus-config