apiVersion: apps/v1
kind: Deployment
metadata:
  name: izdelki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izdelki-service
  template:
    metadata:
      labels:
        app: izdelki-service
    spec:
      containers:
        - image: zigadrab/rso-izdelki-service
          name: izdelki-service
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_SERVER_BASEURL
              value: https://www.songify.si/rso/izdelki
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://songify.si:5433/rso
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rso
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-server.consul:8500
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rso-db-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 70
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 70
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: izdelki-service

spec:
  ports:
    - name: server
      port: 8080
      targetPort: server

  selector:
    app: izdelki-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izdelki-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-example@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /rso/izdelki
            pathType: Prefix
            backend:
              service:
                name: izdelki-service
                port:
                  name: server