apiVersion: apps/v1
kind: Deployment
metadata:
  name: kosarica-microservice-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kosarica-microservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kosarica-microservice
    spec:
      containers:
        - image: divjad123/rso-kosarica-microservice:2022-11-22-12-53-57
          name: kosarica-microservice
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://songify.si:5433/rso
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rso
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rso-db-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: kosarica-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: kosarica-microservice