apiVersion: apps/v1
kind: Deployment
metadata:
  name: kosarica-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kosarica-microservice
  template:
    metadata:
      labels:
        app: kosarica-microservice
    spec:
      containers:
        - image: divjad123/rso-kosarica-microservice:latest
          name: kosarica-microservice
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://localhost:5432/izdelki
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: dbuser
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kosarica-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: kosarica-microservice