apiVersion: apps/v1
kind: Deployment
metadata:
  name: priljubljeni-izdelki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priljubljeni-izdelki-service
  template:
    metadata:
      labels:
        app: priljubljeni-izdelki-service
    spec:
      containers:
        - image: zigadrab/rso-priljubljeni-izdelki-service
          name: priljubljeni-izdelki-service
          env:
            - name: KUMULUZEE_SERVER_BASEURL
              value: https://www.songify.si/rso/priljubljeni-izdelki
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://songify.si:5433/rso
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rso
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rso-db-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: priljubljeni-izdelki-service

spec:
  ports:
    - name: server
      port: 8080
      targetPort: server

  selector:
    app: priljubljeni-izdelki-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: priljubljeni-izdelki-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-example@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /rso/priljubljeni-izdelki
            pathType: Prefix
            backend:
              service:
                name: priljubljeni-izdelki-service
                port:
                  name: server