kumuluzee:
  name: kosarica-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: https://www.songify.si/rso
  datasources:
    - jndi-name: jdbc/KosaricaDS
      connection-url: jdbc:postgresql://songify.si:5433/rso
      #connection-url: jdbc:postgresql://localhost:5432/izdelki
      #connection-url: jdbc:postgresql://host.docker.internal:5432/izdelki
      username: rso
      #username: dbuser
      password: rso_pass
      pool:
        max-size: 20
      #password: postgres
  metrics:
    web-instrumentation:
      - name: kosarica-endpoint
        url-pattern: /v1/kosarica/*
      - name: user-endpoint
        url-pattern: /v1/user/*
integrations:
#  nazadnje:
#    base-url: http://localhost:8081/v1
#  rezervacije:
#    base-url: http://localhost:8082/v1
