kumuluzee:
  name: izdelki-service
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/KosaricaDS
    connection-url: jdbc:postgresql://localhost:5432/izdelki
    #connection-url: jdbc:postgresql://host.docker.internal:5432/izdelki
    username: dbuser
    password: postgres
integrations:
#  nazadnje:
#    base-url: http://localhost:8081/v1
#  rezervacije:
#    base-url: http://localhost:8082/v1
