kumuluzee:
  name: kosarica-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: https://www.songify.si/rso
  datasources:
    - jndi-name: jdbc/KosaricaDS
      connection-url: jdbc:postgresql://songify.si:5433/rso
      username: rso
      password: rso_pass
      pool:
        max-size: 20
  metrics:
    web-instrumentation:
      - name: kosarica-endpoint
        url-pattern: /v1/kosarica/*
      - name: user-endpoint
        url-pattern: /v1/user/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="4b832107-c8b2-462c-920a-bc2e83de6d06-ls.logit.io"
                                    port="28664" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
