name: build with Maven and package as Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN  }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push Docker image
        run: docker buildx build . -t ${{ secrets.DOCKER_USERNAME }}/rso-kosarica-microservice:latest -f ./Dockerfile_with_maven_build --push --platform=linux/arm64,linux/amd64 .